# Intro numpy

In [1]:
numbers = [1,2,3,4,5]

In [4]:
import numpy as np

For finding mean we can use simply below function.

In [5]:
np.mean(numbers)

3.0

Also median is like mean

In [7]:
np.median(numbers)

3.0

For finding standart deviation. We call function with "std"

In [10]:
np.std(numbers)

1.4142135623730951

We can use numpy arrays for faster calculation but this arrays should have big list.

In [20]:
# 1 dimension array
arr = np.array([1,2,3,4,5],float)
print(arr)

# 2 dimension array
arr = np.array([ [1,2,3,4,5],[1,2,3,4,5] ],float)
print(arr)

[1. 2. 3. 4. 5.]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


We can index, slice, and manipulate a Numpy array much like you would with a
a Python list.

In [25]:
array = np.array([1, 4, 5, 8], float)
print(array)
# reach spesific variable
print(array[1])
# reach a lot of variable from third variable 
print(array[:2])
# changing spesivic value
array[2] = 10
print(array)

[1. 4. 5. 8.]
4.0
[1. 4.]
[ 1.  4. 10.  8.]


With 2 dimension array

In [32]:
array = np.array([[1,32,7,5],[2,4,57,0]],float)
print(array)
print("")
# for reach second array we use 1 and for reaching every value we use :
print(array[1,:])
print("")
# reach every array but take third value all of them
print(array[:,2])

[[ 1. 32.  7.  5.]
 [ 2.  4. 57.  0.]]

[ 2.  4. 57.  0.]

[ 7. 57.]


Some arithmatic operations with numpy arrays

In [34]:
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)
print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
