In [43]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [44]:
iris = datasets.load_iris()

In [45]:
iris.data.shape

(150, 4)

In [46]:
iris.target.shape

(150,)

Data has 4 feature and one result.

In [47]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [48]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

In [49]:
X_train.shape

(90, 4)

In [50]:
X_test.shape

(60, 4)

In [51]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2])

In [57]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [58]:
clf.score(X_test, y_test)  

0.9666666666666667

# With another method:

In [59]:
import random

In [60]:
iris2 = datasets.load_iris()

In [69]:
random.shuffle(iris2.data)
data = iris2.data

In [72]:
random.shuffle(iris2.target)
target = iris2.target

In [73]:
print(data)

[[5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.

In [75]:
X_train = data[:int(len(data) * .6)]
X_test = data[int(len(data) * .6):]

In [80]:
y_train = target[:int(len(target) * .6)]
y_test = target[int(len(target) * .6):]

In [81]:
print(X_train.shape)
print(y_train.shape)

(90, 4)
(90,)


In [82]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [83]:
clf.score(X_test, y_test) 

0.4